version: 2
jobs:
  build_test:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.7.0
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: yarn install
      - save_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: |
            yarn lint
            yarn test
workflows:
  version: 2
  build:
    jobs:
      - build_test
